name: adonis-broadcast

services:
  postgres:
    image: postgres:15.1-alpine3.16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine3.16
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
